# Generated by Django 4.1.3 on 2022-11-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_description_alter_blog_headline_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='headline_link',
        ),
    ]
