# Generated by Django 4.1.3 on 2022-11-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_headline_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='headline_link',
            field=models.CharField(default='Topic', max_length=100),
        ),
    ]
