# Generated by Django 4.1.3 on 2022-11-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_headline_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='headline_link',
        ),
    ]
